import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterAll, beforeAll, describe, expect, test } from "vitest";

const root = process.cwd();
const android = join(root, "android");
const signingEnvironmentVariables = [
  "AUTO_AAC_UPLOAD_KEYSTORE",
  "AUTO_AAC_UPLOAD_STORE_PASSWORD",
  "AUTO_AAC_UPLOAD_KEY_ALIAS",
  "AUTO_AAC_UPLOAD_KEY_PASSWORD",
] as const;
const incompleteSigningMessage =
  `Android release signing requires all four environment variables: ${signingEnvironmentVariables.join(", ")}`;

function read(path: string): string {
  return readFileSync(join(root, path), "utf8");
}

function trackedAndroidFiles(): string[] {
  return execFileSync("git", ["ls-files", "--cached", "--others", "--exclude-standard", "android"], {
    cwd: root,
    encoding: "utf8",
  })
    .trim()
    .split(/\r?\n/)
    .filter(Boolean);
}

function findJavaTool(name: string): string {
  const java = spawnSync("java", ["-XshowSettings:properties", "-version"], {
    encoding: "utf8",
  });
  const settings = `${java.stdout ?? ""}\n${java.stderr ?? ""}`;
  const javaHome = settings.match(/^\s*java\.home\s*=\s*(.+)$/m)?.[1].trim();
  if (java.status !== 0 || !javaHome) throw new Error(`Unable to locate Java home:\n${settings}`);
  const executable = process.platform === "win32" ? `${name}.exe` : name;
  return join(javaHome, "bin", executable);
}

function gradleSigningReport(signing: Partial<Record<(typeof signingEnvironmentVariables)[number], string>>) {
  const env = { ...process.env };
  for (const name of signingEnvironmentVariables) delete env[name];
  Object.assign(env, signing);

  if (!env.ANDROID_HOME && !env.ANDROID_SDK_ROOT && process.platform === "win32") {
    const defaultSdk = env.LOCALAPPDATA ? join(env.LOCALAPPDATA, "Android", "Sdk") : "";
    if (defaultSdk && existsSync(defaultSdk)) env.ANDROID_HOME = defaultSdk;
  }

  const executable = process.platform === "win32" ? "cmd.exe" : "./gradlew";
  const args =
    process.platform === "win32"
      ? ["/d", "/s", "/c", "gradlew.bat", "--no-daemon", ":app:signingReport"]
      : ["--no-daemon", ":app:signingReport"];
  const result = spawnSync(executable, args, {
    cwd: android,
    env,
    encoding: "utf8",
    timeout: 120_000,
  });

  return {
    status: result.status,
    output: `${result.stdout ?? ""}\n${result.stderr ?? ""}`,
  };
}

describe("Android TWA release configuration", () => {
  let temporaryDirectory: string;
  let syntheticKeystore: string;

  beforeAll(() => {
    temporaryDirectory = mkdtempSync(join(tmpdir(), "auto-aac-signing-"));
    syntheticKeystore = join(temporaryDirectory, "synthetic-upload.jks");
    execFileSync(
      findJavaTool("keytool"),
      [
        "-genkeypair",
        "-keystore",
        syntheticKeystore,
        "-storetype",
        "JKS",
        "-storepass",
        "synthetic-store-password",
        "-keypass",
        "synthetic-key-password",
        "-alias",
        "synthetic-upload",
        "-dname",
        "CN=Auto AAC Signing Test",
        "-validity",
        "1",
        "-keyalg",
        "RSA",
        "-noprompt",
      ],
      { stdio: "ignore" },
    );
  });

  afterAll(() => rmSync(temporaryDirectory, { recursive: true, force: true }));

  test("contains a complete production Android project", () => {
    expect(existsSync(android), "android/ must be generated by Bubblewrap").toBe(true);
    expect(existsSync(join(android, "twa-manifest.json"))).toBe(true);
    expect(existsSync(join(android, "gradlew"))).toBe(true);
    expect(existsSync(join(android, "gradlew.bat"))).toBe(true);

    const config = read("android/twa-manifest.json");
    const appGradle = read("android/app/build.gradle");
    const manifest = read("android/app/src/main/AndroidManifest.xml");

    expect(config).toContain('"packageId": "com.yangisu.autoaac"');
    expect(config).toContain('"host": "auto-aac.vercel.app"');
    expect(config).toContain('"startUrl": "/"');
    expect(config).toContain('"name": "Auto AAC"');
    expect(config).toContain('"launcherName": "Auto AAC"');
    expect(config).toContain('"enableNotifications": false');
    expect(config).toContain('"enableSiteSettingsShortcut": false');
    expect(config).toContain('"isChromeOSOnly": false');

    expect(appGradle).toMatch(/namespace\s+["']com\.yangisu\.autoaac["']/);
    expect(appGradle).toMatch(/applicationId\s+["']com\.yangisu\.autoaac["']/);
    expect(appGradle).toMatch(/compileSdk(?:Version)?\s+35\b/);
    expect(appGradle).toMatch(/targetSdk(?:Version)?\s+35\b/);
    expect(appGradle).toMatch(/versionCode\s+1\b/);
    expect(appGradle).toMatch(/versionName\s+["']1["']/);
    expect(appGradle).toContain("launcherName: 'Auto AAC'");
    expect(appGradle).toContain(
      "implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'",
    );

    const permissions = [...manifest.matchAll(/uses-permission android:name="([^"]+)"/g)].map(
      ([, permission]) => permission,
    );
    expect(permissions).toEqual(["android.permission.INTERNET"]);

    for (const icon of [
      "android/app/src/main/res/mipmap-hdpi/ic_launcher.png",
      "android/app/src/main/res/mipmap-mdpi/ic_launcher.png",
      "android/app/src/main/res/mipmap-xhdpi/ic_launcher.png",
      "android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png",
      "android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png",
    ]) {
      expect(existsSync(join(root, icon)), `${icon} must exist`).toBe(true);
    }
  });

  test("tracks no development origins, signing secrets, or delegated features", () => {
    const files = trackedAndroidFiles();
    expect(files.length).toBeGreaterThan(0);

    const trackedConfig = files
      .filter((file) => /\.(?:gradle|json|properties|xml)$/i.test(file))
      .map((file) => read(file))
      .join("\n");

    expect(trackedConfig).not.toMatch(/localhost|127\.0\.0\.1/i);
    const vercelHosts = [...trackedConfig.matchAll(/https?:\/\/([^/\s"'\\]+\.vercel\.app)/gi)].map(
      ([, host]) => host.toLowerCase(),
    );
    expect(new Set(vercelHosts)).toEqual(new Set(["auto-aac.vercel.app"]));
    expect(trackedConfig).not.toMatch(/BILLING|ACCESS_(?:COARSE|FINE)_LOCATION|POST_NOTIFICATIONS/);
    expect(trackedConfig).not.toMatch(/(?:storePassword|keyPassword|keyAlias)\s+["'][^"']+["']/i);
    expect(trackedConfig).not.toMatch(/storeFile\s+file\s*\(\s*["'][^"']+["']\s*\)/i);
    expect(trackedConfig).not.toMatch(/["'][^"']*\.(?:jks|keystore)["']|[A-Za-z]:\\/i);

    for (const file of files) {
      expect(file).not.toMatch(/\.(?:jks|keystore|apk|aab)$/i);
      expect(file).not.toMatch(/key\.properties$/i);
    }
  });

  test("configures release signing from exactly the four upload-key environment variables", () => {
    const appGradle = read("android/app/build.gradle");
    const environmentVariables = [
      ...appGradle.matchAll(/System\.getenv\(\s*["']([^"']+)["']\s*\)/g),
    ].map(([, name]) => name);

    expect(environmentVariables).toEqual(signingEnvironmentVariables);
    expect(appGradle).toMatch(
      /signingConfigs\s*\{\s*if\s*\(hasReleaseSigning\)\s*\{\s*release\s*\{/s,
    );
    expect(appGradle).toMatch(/storeFile\s+file\(releaseSigning\.keystore\)/);
    expect(appGradle).toMatch(/storePassword\s+releaseSigning\.storePassword/);
    expect(appGradle).toMatch(/keyAlias\s+releaseSigning\.keyAlias/);
    expect(appGradle).toMatch(/keyPassword\s+releaseSigning\.keyPassword/);
    expect(appGradle).toMatch(
      /buildTypes\s*\{\s*release\s*\{[\s\S]*?if\s*\(hasReleaseSigning\)\s*\{\s*signingConfig\s+signingConfigs\.release\s*\}/,
    );
  });

  test(
    "leaves release unsigned when every signing variable is unset",
    () => {
      const result = gradleSigningReport({});

      expect(result.status, result.output).toBe(0);
      expect(result.output).toMatch(/Variant: release[\s\S]*?Config: null/);
    },
    120_000,
  );

  test(
    "configures release signing when every variable is nonblank and the JKS is valid",
    () => {
      const result = gradleSigningReport({
        AUTO_AAC_UPLOAD_KEYSTORE: syntheticKeystore,
        AUTO_AAC_UPLOAD_STORE_PASSWORD: "synthetic-store-password",
        AUTO_AAC_UPLOAD_KEY_ALIAS: "synthetic-upload",
        AUTO_AAC_UPLOAD_KEY_PASSWORD: "synthetic-key-password",
      });

      expect(result.status, result.output).toBe(0);
      expect(result.output).toMatch(/Variant: release[\s\S]*?Config: release/);
      expect(result.output).toContain(`Store: ${syntheticKeystore}`);
      expect(result.output).toContain("Alias: synthetic-upload");
    },
    120_000,
  );

  test(
    "rejects a partial release signing environment during Gradle configuration",
    () => {
      const result = gradleSigningReport({
        AUTO_AAC_UPLOAD_KEYSTORE: syntheticKeystore,
        AUTO_AAC_UPLOAD_STORE_PASSWORD: "synthetic-store-password",
      });

      expect(result.status).not.toBe(0);
      expect(result.output).toContain(incompleteSigningMessage);
      expect(result.output).not.toContain("synthetic-store-password");
    },
    120_000,
  );

  test(
    "rejects whitespace values mixed with nonblank signing variables during configuration",
    () => {
      const result = gradleSigningReport({
        AUTO_AAC_UPLOAD_KEYSTORE: syntheticKeystore,
        AUTO_AAC_UPLOAD_STORE_PASSWORD: "   ",
        AUTO_AAC_UPLOAD_KEY_ALIAS: "synthetic-upload",
        AUTO_AAC_UPLOAD_KEY_PASSWORD: "synthetic-key-password",
      });

      expect(result.status).not.toBe(0);
      expect(result.output).toContain(incompleteSigningMessage);
      expect(result.output).not.toContain("synthetic-key-password");
    },
    120_000,
  );

  test("documents signed release builds and upload-certificate verification", () => {
    const readme = read("android/README.md");

    for (const name of [
      "AUTO_AAC_UPLOAD_KEYSTORE",
      "AUTO_AAC_UPLOAD_STORE_PASSWORD",
      "AUTO_AAC_UPLOAD_KEY_ALIAS",
      "AUTO_AAC_UPLOAD_KEY_PASSWORD",
    ]) {
      expect(readme).toContain(`$env:${name}`);
    }
    expect(readme).toContain(".\\gradlew.bat clean :app:bundleRelease");
    expect(readme).toMatch(/jarsigner\s+-verify/);
    expect(readme).toMatch(/\$verificationText\s+-match\s+["']jar is unsigned["']/i);
    expect(readme).toMatch(/\$verificationText\s+-notmatch\s+["']jar verified["']/i);
    expect(readme).toMatch(/keytool\s+-list\s+-v/);
    expect(readme).toMatch(/SHA-?256 fingerprint.*Play Console.*upload certificate/is);
    expect(readme).toMatch(/try\s*\{[\s\S]*?\}\s*finally\s*\{/);
    const finallyBlock = readme.match(/finally\s*\{([\s\S]*?)\}/)?.[1] ?? "";
    for (const name of signingEnvironmentVariables) {
      expect(finallyBlock).toContain(`Remove-Item Env:${name} -ErrorAction SilentlyContinue`);
    }
    expect(readme).toMatch(/outside Git/i);
    expect(readme).toMatch(/back(?:ed)? up securely/i);
    expect(readme).toMatch(/Play App Signing certificate.*upload certificate/is);
  });
});
