import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, test } from "vitest";

const root = process.cwd();
const android = join(root, "android");

function read(path: string): string {
  return readFileSync(join(root, path), "utf8");
}

function trackedAndroidFiles(): string[] {
  return execFileSync("git", ["ls-files", "--cached", "--others", "--exclude-standard", "android"], {
    cwd: root,
    encoding: "utf8",
  })
    .trim()
    .split(/\r?\n/)
    .filter(Boolean);
}

describe("Android TWA release configuration", () => {
  test("contains a complete production Android project", () => {
    expect(existsSync(android), "android/ must be generated by Bubblewrap").toBe(true);
    expect(existsSync(join(android, "twa-manifest.json"))).toBe(true);
    expect(existsSync(join(android, "gradlew"))).toBe(true);
    expect(existsSync(join(android, "gradlew.bat"))).toBe(true);

    const config = read("android/twa-manifest.json");
    const appGradle = read("android/app/build.gradle");
    const manifest = read("android/app/src/main/AndroidManifest.xml");

    expect(config).toContain('"packageId": "com.yangisu.autoaac"');
    expect(config).toContain('"host": "auto-aac.vercel.app"');
    expect(config).toContain('"startUrl": "/"');
    expect(config).toContain('"name": "Auto AAC"');
    expect(config).toContain('"launcherName": "Auto AAC"');
    expect(config).toContain('"enableNotifications": false');
    expect(config).toContain('"enableSiteSettingsShortcut": false');
    expect(config).toContain('"isChromeOSOnly": false');

    expect(appGradle).toMatch(/namespace\s+["']com\.yangisu\.autoaac["']/);
    expect(appGradle).toMatch(/applicationId\s+["']com\.yangisu\.autoaac["']/);
    expect(appGradle).toMatch(/compileSdk(?:Version)?\s+35\b/);
    expect(appGradle).toMatch(/targetSdk(?:Version)?\s+35\b/);
    expect(appGradle).toMatch(/versionCode\s+1\b/);
    expect(appGradle).toMatch(/versionName\s+["']1["']/);
    expect(appGradle).toContain("launcherName: 'Auto AAC'");
    expect(appGradle).toContain(
      "implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'",
    );

    const permissions = [...manifest.matchAll(/uses-permission android:name="([^"]+)"/g)].map(
      ([, permission]) => permission,
    );
    expect(permissions).toEqual(["android.permission.INTERNET"]);

    for (const icon of [
      "android/app/src/main/res/mipmap-hdpi/ic_launcher.png",
      "android/app/src/main/res/mipmap-mdpi/ic_launcher.png",
      "android/app/src/main/res/mipmap-xhdpi/ic_launcher.png",
      "android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png",
      "android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png",
    ]) {
      expect(existsSync(join(root, icon)), `${icon} must exist`).toBe(true);
    }
  });

  test("tracks no development origins, signing secrets, or delegated features", () => {
    const files = trackedAndroidFiles();
    expect(files.length).toBeGreaterThan(0);

    const trackedConfig = files
      .filter((file) => /\.(?:gradle|json|properties|xml)$/i.test(file))
      .map((file) => read(file))
      .join("\n");

    expect(trackedConfig).not.toMatch(/localhost|127\.0\.0\.1/i);
    const vercelHosts = [...trackedConfig.matchAll(/https?:\/\/([^/\s"'\\]+\.vercel\.app)/gi)].map(
      ([, host]) => host.toLowerCase(),
    );
    expect(new Set(vercelHosts)).toEqual(new Set(["auto-aac.vercel.app"]));
    expect(trackedConfig).not.toMatch(/BILLING|ACCESS_(?:COARSE|FINE)_LOCATION|POST_NOTIFICATIONS/);
    expect(trackedConfig).not.toMatch(/storePassword|keyPassword|\.jks|\.keystore|[A-Za-z]:\\/i);

    for (const file of files) {
      expect(file).not.toMatch(/\.(?:jks|keystore|apk|aab)$/i);
      expect(file).not.toMatch(/key\.properties$/i);
    }
  });
});
